Django_APP/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from notehub.views import home, signup_view, login_view, logout_view

urlpatterns = [

    path('admin/', admin.site.urls),
    url(r'^$', home, name='home'),
    url(r'^signup/', signup_view, name='signup'),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^notehub/', include('notehub.urls')),

]

urlpatterns += staticfiles_urlpatterns()

notehub/urls.py
from django.conf.urls import url

from notehub.views import documents_list, document_detail, add_document_view, user_panel_view, add_exam_view, \
    add_exercise_view, add_note_view, exam_list, exercise_list, note_list, valorate_view

app_name = 'notehub'

urlpatterns = [
    url(r'^$', user_panel_view, name='user_panel'),
    url(r'^document_list', documents_list, name='list'),
    url(r'^exam_list', exam_list, name='exam_list'),
    url(r'^exercise_list', exercise_list, name='exercise_list'),
    url(r'^note_list', note_list, name= 'note_list'),
    url(r'^addDocument/', add_document_view, name='addDocument'),
    url(r'^addExam/', add_exam_view, name='addExam'),
    url(r'^addExercise/', add_exercise_view, name='addExercise'),
    url(r'^addNote/', add_note_view, name='addNote'),
    url(r'^(?P<id>[\w-]+)/$', document_detail, name='detail'), #always last
    url(r'^(?P<id>[\w-]+)/valorate/$', valorate_view, name='valorate'),
]

notehub/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import date


# Create your models here.

class Student(User):
    DNI = models.CharField(max_length=20, unique=True)
    degree = models.CharField(max_length=50)
    starting_date = models.DateField()
    #subjects = models.TextField()
    average_valoration = models.FloatField(blank=True, null=True)

    def __str__(self):
        return u"%s" % self.username

    #def get_absolute_url(self):
     #   return reverse('myrestaurants:dish_detail',
     #                  kwargs={'pkr': self.restaurant.pk, 'pk': self.pk})


class Document(models.Model):
    name = models.CharField(max_length=50)
    creator = models.ForeignKey(Student, on_delete=models.CASCADE)
    content = models.TextField(blank=True, null=True)
    degree = models.CharField(max_length=50)
    subject = models.CharField(max_length=50)
    last_update = models.DateField(default=date.today)
    average_valoration = models.IntegerField(default=0)

    def __str__(self):
        return u"%s" % self.degree + " | " + self.subject + " | " + self.name

    #def get_absolute_url(self):
     #   return reverse('notehub:document',
      #                 kwargs={'pkr': self.document.pk, 'pk': self.pk})


class Exercise(Document):
    unit = models.IntegerField()
    corrected = models.BooleanField(default=False)


class Exam(Document):
    PARCIAL_NUMBER = ((1, 'First'), (2, 'Second'))
    date = models.DateField()
    parcial = models.PositiveSmallIntegerField(choices=PARCIAL_NUMBER)
    exercices = models.ManyToManyField(Exercise)
    solved = models.BooleanField(default=False)


class Note(Document):
    #POSSIBLE_DEGREES = ((1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five'))
    unit = models.IntegerField()
    date = models.DateField()
    #schematization_degree = models.PositiveSmallIntegerField(blank=False, choices=POSSIBLE_DEGREES)


class Valoration(models.Model):
    RATING_CHOICES = ((1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five'))
    rating = models.PositiveSmallIntegerField(blank=False, choices=RATING_CHOICES)
    document = models.ForeignKey(Document, on_delete=models.CASCADE)
    comment = models.TextField()
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return u"%s" % "Valoration " + str(self.id) + " of " + self.document.name

notehub/forms.py
from datetime import datetime

from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from django import forms
from django.core.exceptions import ValidationError
from notehub.models import Student, Exam, Exercise, Note


class SignupForm(UserCreationForm):
    username = forms.CharField(max_length=20, required=True)
    DNI = forms.CharField(max_length=20, required=True)
    degree = forms.CharField(max_length=50, required=True)
    starting_date = forms.DateField(required=True)

    class Meta:
        model = Student
        fields = ['username', 'password1', 'password2', 'DNI', 'degree', 'starting_date']

    def clean_renewal_date(self):
        start = self.cleaned_data['starting_date']
        #passw = self.cleaned_data['password1']
        #passw2 = self.cleaned_data['password2']

        # Check date is not in past.
        if start < datetime.date.today():
            raise ValidationError('Invalid date')

        #if passw != passw2:
         #   raise ValidationError('Passwords do not match')


class AddExamForm(ModelForm):
    PARCIAL_NUMBER = ((1, 'First'), (2, 'Second'))
    name = forms.CharField(max_length=50, required=True)
    content = forms.CharField(widget=forms.Textarea, required=True)
    degree = forms.CharField(max_length=50, required=True)
    subject = forms.CharField(max_length=50, required=True)
    date = forms.DateField(required=True)
    parcial = forms.CheckboxSelectMultiple(choices=PARCIAL_NUMBER)
    solved = forms.BooleanField(required=False)

    class Meta:
        model = Exam
        fields = ['name', 'content', 'degree', 'subject', 'date', 'parcial', 'solved']


class AddExerciseForm(ModelForm):
    name = forms.CharField(max_length=50, required=True)
    content = forms.CharField(max_length=2000, required=True)
    degree = forms.CharField(max_length=50, required=True)
    subject = forms.CharField(max_length=50, required=True)
    unit = forms.IntegerField(required=True)
    corrected = forms.BooleanField(required=False)

    class Meta:
        model = Exercise
        fields = ['name', 'content', 'degree', 'subject', 'unit', 'corrected']


class AddNoteForm(ModelForm):
    name = forms.CharField(max_length=50, required=True)
    content = forms.CharField(max_length=2000, required=True)
    degree = forms.CharField(max_length=50, required=True)
    subject = forms.CharField(max_length=50, required=True)
    unit = forms.IntegerField(required=True)
    date = forms.DateField(required=True)

    class Meta:
        model = Note
        fields = ['name', 'content', 'degree', 'subject', 'unit', 'date']

notehub/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from notehub.forms import SignupForm, AddExerciseForm, AddNoteForm, AddExamForm
from django.utils import timezone
from django.urls import reverse
# Create your views here.
from django.views.generic import DetailView

from notehub.models import Student, Document, Exam, Note, Exercise


def home(request):
    template_name = 'notehub/home.html'
    return render(request, template_name, context={'title': 'app_name'})

@login_required(login_url="/login/")
def documents_list(request):
    documents = Document.objects.all().order_by('id')
    template_name = 'notehub/documents_list.html'
    return render(request, template_name, {'documents': documents})

@login_required(login_url="/login/")
def exam_list(request):
    exams = Exam.objects.all().order_by('id')
    template_name = 'notehub/exam_list.html'
    return render(request, template_name, {'exams': exams})

@login_required(login_url="/login/")
def note_list(request):
    notes = Note.objects.all().order_by('id')
    template_name = 'notehub/note_list.html'
    return render(request, template_name, {'notes': notes})

@login_required(login_url="/login/")
def exercise_list(request):
    exercises = Exercise.objects.all().order_by('id')
    template_name = 'notehub/exercise_list.html'
    return render(request, template_name, {'exercises': exercises})

@login_required(login_url="/login/")
def document_detail(request, id):
    document = Document.objects.get(id=id)
    return render(request, 'notehub/document_detail.html', {'document': document})
    # return HttpResponse(id)

@login_required(login_url="/login/")
def user_panel_view(request):
    return render(request, 'notehub/user_panel.html')


@login_required(login_url="/login/")
def add_document_view(request):
    template_name = 'notehub/add_document.html'
    return render(request, template_name, context={'title': 'addDocument'})


def signup_view(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('notehub:user_panel')
    else:
        form = SignupForm()
    return render(request, 'notehub/signup.html', context={'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('notehub:user_panel')
    else:
        form = AuthenticationForm()
    return render(request, 'notehub/login.html', context={'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

@login_required(login_url="/login/")
def add_exam_view(request):
    if request.method == 'POST':
        form = AddExamForm(request.POST)
        if form.is_valid():
            exam = form.save(commit=False)
            user = get_object_or_404(Student, Q(id=request.user.id))
            exam.creator = user
            exam.save()
            return redirect('notehub:exam_list')
    else:
        form = AddExamForm()
    return render(request, 'notehub/add_Exam.html', context={'form': form})

@login_required(login_url="/login/")
def add_exercise_view(request):
    if request.method == 'POST':
        form = AddExerciseForm(request.POST)
        if form.is_valid():
            exercise = form.save(commit=False)
            user = get_object_or_404(Student, Q(id=request.user.id))
            exercise.creator = user
            exercise.save()
            return redirect('notehub:exercise_list')
    else:
        print('ERROR')
        form = AddExerciseForm()
    return render(request, 'notehub/add_Exercice.html', context={'form': form})

@login_required(login_url="/login/")
def add_note_view(request):
    if request.method == 'POST':
        form = AddNoteForm(request.POST)
        if form.is_valid():
            note = form.save(commit=False)
            user = get_object_or_404(Student, Q(id=request.user.id))
            note.creator = user
            note.save()
            return redirect('notehub:note_list')
    else:
        form = AddNoteForm()
    return render(request, 'notehub/add_Note.html', context={'form': form})

def valorate_view(request):
    document = Document.objects.get(id=id)
    template_name = 'notehub/valorate.html'
    return render(request, template_name, {'document': document})

templates/notehub/add_Exam.html
{% extends 'notehub/base_layout.html' %}

{% block content %}
    <ul>
        <li>
            <form class="panel-link" action="{% url 'notehub:user_panel' %}" method="post">
                {% csrf_token %}
                <button type="submit">Home</button>
            </form>
        </li>
    </ul>
    <hr />
    <h1>Add Exam</h1>
    <form class="site-form"  method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Upload">
    </form>
{% endblock %}

templates/notehub/add_Exercice.html
{% extends 'notehub/base_layout.html' %}

{% block content %}
     <ul>
        <li>
            <form class="panel-link" action="{% url 'notehub:user_panel' %}" method="post">
                {% csrf_token %}
                <button type="submit">Home</button>
            </form>
        </li>
     </ul>
    <hr />
    <h1>Sign up</h1>
    <form class="site-form"  method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Upload">
    </form>
{% endblock %}

templates/notehub/add_Note.html
{% extends 'notehub/base_layout.html' %}

{% block content %}
    <ul>
        <li>
            <form class="panel-link" action="{% url 'notehub:user_panel' %}" method="post">
                {% csrf_token %}
                <button type="submit">Home</button>
            </form>
        </li>
    </ul>
    <hr />
    <h1>Add Note</h1>
    <form class="site-form"  method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Upload">
    </form>
{% endblock %}

templates/notehub/add_document.html
{% extends 'notehub/base_layout.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <ul>
        <li>
            <form class="panel-link" action="{% url 'notehub:user_panel' %}" method="post">
                {% csrf_token %}
                <button type="submit">Home</button>
            </form>
        </li>
    </ul>
    <meta charset="UTF-8">
</head>
<body>
    <hr />
    <h2>Choose the kind of document you want to upload</h2>
    <br>
    <a href="/notehub/addExercise">Exercise</a>
    <hr />
    <a href="/notehub/addExam">Exam</a>
    <hr />
    <a href="/notehub/addNote">Note</a>
{% endblock %}
</body>
</html>

templates/notehub/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Notehub</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>
    <body>
        <div class="wrapper">

            <nav>
                <ul>
                    <li>
                        <form class="logout-link" action="{% url 'logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                </ul>
            </nav>

            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

templates/notehub/document_detail.html
{% extends 'notehub/base_layout.html' %}

{% block content %}
    <ul>
        <li>
            <form class="panel-link" action="{% url 'notehub:user_panel' %}" method="post">
                {% csrf_token %}
                <button type="submit">Home</button>
            </form>
        </li>
    </ul>
    <div class="document-detail">
        <div class="document">
            <h2>{{ document.name }}</h2>
            <p>{{ document.subject }}</p>
            <p>{{ document.content }}</p>
        </div>
    </div>
{% endblock %}

templates/notehub/documents_list.html
{% extends 'notehub/base_layout.html' %}

{% block content %}
    <ul>
        <li>
            <form class="panel-link" action="{% url 'notehub:user_panel' %}" method="post">
                {% csrf_token %}
                <button type="submit">Home</button>
            </form>
        </li>
    </ul>
    <h1>Document list</h1>
    <div class="documents">
        {% for document in documents%}
            <div class="document">
                <h2><a href="{% url 'notehub:detail' id=document.id %}">{{ document.name }}</a></h2>
                <p>{{ document.last_update }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/notehub/exam_list.html
{% extends 'notehub/base_layout.html' %}

{% block content %}
    <ul>
        <li>
            <form class="panel-link" action="{% url 'notehub:user_panel' %}" method="post">
                {% csrf_token %}
                <button type="submit">Home</button>
            </form>
        </li>
    </ul>
    <hr />
    <h1>Exams list</h1>
    <div class="exams">
        {% for exam in exams %}
            <div class="exam">
                <h2><a href="{% url 'notehub:detail' id=exam.id %}">{{ exam.name }}</a></h2>
                <p>{{ exam.last_update }}</p>
            </div>
            <hr />
        {% endfor %}
    </div>
{% endblock %}

templates/notehub/exercise_list.html
{% extends 'notehub/base_layout.html' %}

{% block content %}
    <ul>
        <li>
            <form class="panel-link" action="{% url 'notehub:user_panel' %}" method="post">
                {% csrf_token %}
                <button type="submit">Home</button>
            </form>
        </li>
    </ul>
    <hr />
    <h1>Exercises list</h1>
    <div class="exercises">
        {% for exercise in exercises %}
            <div class="exercise">
                <h2><a href="{% url 'notehub:detail' id=exercise.id %}">{{ exercise.name }}</a></h2>
                <p>{{ exercise.last_update }}</p>
            </div>
            <hr />
        {% endfor %}
    </div>
{% endblock %}

templates/notehub/home.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
     <link rel="stylesheet" href="{% static "welcome.css" %}" />
     <title>{% block title %} Home{% endblock %}</title>
     <h1 align="center"><img src="{% static 'logo.png' %}" height="80" width="200"> </h1>
</head>
<body>
<div id="header">
     {% block header %}
     {% endblock %}
</div>
<div id="content">
     {% block content %}
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
     {% endblock %}
</div>
<div align="center">
<a href="/admin">Access as Admin</a>
<hr />
<a href="/signup">Register</a>
<hr />
<a href="/login">Sign in</a>
</div>
<div id="footer">{% block footer %}{% endblock %}</div>
</body>
</html>

templates/notehub/login.html
{% extends 'notehub/base_layout.html' %}

{% block content %}
    <h1>Log in</h1>
    <form class="site-form" action="/login/" method="post">
        {% csrf_token %}
        {{form}}
        {%  if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <input type="submit" value="Login">
    </form>
{% endblock %}

templates/notehub/note_list.html
{% extends 'notehub/base_layout.html' %}

{% block content %}
    <ul>
        <li>
            <form class="panel-link" action="{% url 'notehub:user_panel' %}" method="post">
                {% csrf_token %}
                <button type="submit">Home</button>
            </form>
        </li>
    </ul>
    <hr />
    <h1>Notes list</h1>
    <div class="notes">
        {% for note in notes %}
            <div class="note">
                <h2><a href="{% url 'notehub:detail' id=note.id %}">{{ note.name }}</a></h2>
                <p>{{ note.last_update }}</p>
            </div>
            <hr />
        {% endfor %}
    </div>
{% endblock %}

templates/notehub/signup.html
{% extends 'notehub/base_layout.html' %}

{% block content %}
    <h1>Sign up</h1>
    <form class="site-form" action="/signup/" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

templates/notehub/user_panel.html
{% extends 'notehub/base_layout.html' %}

{% block content %}
    <meta charset="UTF-8">
    <title>NOTEHUB</title>
    <a href="/notehub/addDocument">Add a Document</a>
    <hr />
    <a href="/notehub/exam_list">View Exams</a>
    <hr />
    <a href="/notehub/exercise_list">View Exercises</a>
    <hr />
    <a href="/notehub/note_list">View Notes</a>
    <hr />
{% endblock %}